<TERMSScreen>
    id: terms
    name: 'terms_screen'
    Terms_box:
        id:terms_box


<Terms_box>
    id:terms_box
    orientation: "horizontal"
    BoxLayout:
        orientation: 'vertical'
        Label:
            id: terms_label
            text: "here comes the terms"
        CheckBox:
            id: terms_check
        Button:
            id: agree
            text: 'agree'
    Side_box:
        id: side_box