#:import Label kivy.uix.button.Button

<RecycleViewRow>
    id: RecycleViewRow
    on_press: root.open_offer_window()


<Offers_Screen>
    background_color: (0,0,0,0)
    id:scrolls
    MDGridLayout:
        cols: 1
        row_default_height: (self.width - self.cols*self.spacing[0]) / self.cols
        row_force_default: True
        adaptive_height: True
        id: scroll_box
        size_hint: 1,.9
        #orientation: 'vertical'
        spacing:10